# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models/payment.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'models/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14models/payment.proto\"T\n\nPayRequest\x12\x13\n\x0b\x63\x61rd_number\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x02\"\x1a\n\x08PayReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32*\n\x07Payment\x12\x1f\n\x03Pay\x12\x0b.PayRequest\x1a\t.PayReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYREQUEST']._serialized_start=24
  _globals['_PAYREQUEST']._serialized_end=108
  _globals['_PAYREPLY']._serialized_start=110
  _globals['_PAYREPLY']._serialized_end=136
  _globals['_PAYMENT']._serialized_start=138
  _globals['_PAYMENT']._serialized_end=180
# @@protoc_insertion_point(module_scope)
